anholt/libepoxy

configure.ac, src/dispatch_common.h
OS X support shouldn't depend on X11 being installed on the host.
Removes the X11 dependency.
=> Adds support for OS X without X11.

src/gen_dispatch.py
Hi,
I am opening this pull request as we would still like to support building GTK+ entirely with Visual Studio, and there are still many people that are not yet able to go up to Visual Studio 2013.
At this point, the main thing that needs to be done is to avoid named initializers, but
instead initialize the structs in old-school C89 way, so the changes needed here are quite small.
The generated code may not look that robust, but since this is generated
code, I think this is not that much an issue; when the Khronos registry gets
updated, all that is needed is that the code gets re-generated, and we have the
items in the right order.
With blessings, thank you!
=> src/gen_dispatch.py: Make Generated Code Build Under pre-2013 Visual Studio

test/dlwrap.c
See sysdeps/unix/sysv/linux/arm/libdl.abilist in glibc
=> dlwrap: add GLIBC_2.4 version to be able to run tests from ARM

src/gen_dispatch.py
The newest gl.xml from the Khronos registry is too large to fit in the array size. Changed indices from 16-bit to 32-bit and had to change ridiculously enormous string into ridiculously enormous array of single characters as it was over the string size limit.
=> support newer/larger gl.xml

src/gen_dispatch.py
While working on a game I discovered that epoxy won't resolve glBindRenderbuffer in OpenGL 2.1 contexts even though glBindRenderbufferEXT is available.
Seeing that there already is a similar fix for glBindFramebufferEXT, I added it to the half_aliases array in gen_dispatch.py. Without this fix, you won't be able to make use of FBOs if only GL_EXT_framebuffer_object is available.
=> Add glBindRenderbufferEXT to half_aliases

autogen.sh
If the '--force' switch is not passed to autoreconf, the autotools will
try to reuse the generated files committed in the Git repo, which hard
code the names and versions of the tools originally used to generate
them.
=> build: Force replacing autotools generated files

src/dispatch_common.c
Binding an API does not change the type of the current context. Even if
it did, EGL 1.5 treats EGL_OPENGL_API and EGL_OPENGLES_API as identical
for this purpose.  If you want to know properties of the current
context, query it.
Signed-off-by: Adam Jackson ajax@redhat.com
=> egl: Fix the query for the current context's API

include/epoxy/egl.h, include/epoxy/glx.h, src/dispatch_common.c, src/dispatch_common.h, src/dispatch_egl.c, src/dispatch_glx.c
=> Platform detection

include/epoxy/meson.build, meson.build, src/meson.build
On UNIX-like OSes, the OS will read the shebang and use the correct interpreter, and on Windows, Meson will read the shebang and use the correct interpreter.
Adding it manually will cause python to try to interpret python.exe
With this change, libepoxy builds and the tests pass with MSVC on Windows for me.
=> meson: Don't call find_program objects with python

include/epoxy/egl.h, include/epoxy/gl.h, include/epoxy/glx.h, include/epoxy/wgl.h
Commit 0625a74d69f762df8d411bc0451927424aee1f2c moved the C++ guards
after the inclusion of the generated headers, which was an unintended
behavioural change and now requires header guards around the inclusion
of Epoxy headers.
Fixes: #106
=> Add C++ guards around generated headers

src/meson.build
Autotools automatically adds version related linker flags on macOS that
are not related to the version information. Since we want to maintain
binary compatibility, we should do the same when building on macOS.
Fixes: #108
=> Add explicit version flags for macOS builds

test/dlwrap.c
dlsym on aarch64 has version GLIBC_2.17.
=> test: Fix dlwrap on aarch64

meson.build
MSVC 2013 failed to build libepoxy due to error C2054: expected '(' to follow 'inline'.
=> Fix build on MSVC

meson.build
It seems bumping to 0.38.1 was too relaxed, and evidently I didn't thoroughly test the change.
Let's bump to 0.39.1, as it's the same version we use for CI.
=> Update required version to 0.39.1

meson.build
Haiku is a operating system that targets personal computing and is inspired by BeOS. This commit disables building glx on Haiku, allowing it to build libepoxy successfully. I also tested the build on Haiku and it passes all tests.
=> Add support for building on Haiku.

src/meson.build
Just saw this happening on macOS:
````
[9/13] Linking target src/libepoxy.0.dylib
FAILED: src/libepoxy.0.dylib 
clang  -o src/libepoxy.0.dylib 'src/epoxy@sha/src_gl_generated_dispatch.c.o' 'src/epoxy@sha/dispatch_common.c.o' '-shared' '-install_name' '/private/tmp/libepoxy-20170612-40467-rny9re/libepoxy-1.4.3/build/src/libepoxy.dylib' '-compatibility_version=1' '-current_version=1.0' '-ldl' '-Wl,-rpath,/private/tmp/libepoxy-20170612-40467-rny9re/libepoxy-1.4.3/build/src'  
ld: malformed 32-bit x.y.z version number: =1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
````
Fix was simply replacing the equal signs with spaces.
=> meson.build: fix macOS common_ldflags

src/dispatch_common.c
glvnd has the rather nice property that GLX and (desktop) GL are
available in separate libraries. As an example this would allow an EGL
app to use desktop GL without any X11 libraries. Fix up our dlopens to
prefer the glvnd libraries if available and fall back to the old ABI if
not.
=> dispatch: Learn about glvnd

src/dispatch_common.c
This doesn't _quite_ eliminate X11 libraries from EGL applications, since
Mesa's libEGL has an X11 backend. But it does eliminate libGL and libGLX.
=> Try even harder to not load GLX

src/gen_dispatch.py
The EGL API update from d11104f2b5 introduced a dependency on the
EGL_CAST() macro, provided by an updated eglplatform.h. Given that we
don't provide eglplatform.h, add a fallback definition for if we're
building against Mesa 17.0.x or similar.
https://bugs.gentoo.org/show_bug.cgi?id=623926
=> Add fallback definition for EGL_CAST

include/epoxy/gl.h, src/dispatch_common.c, src/dispatch_common.h, src/gen_dispatch.py
I'd like to use epoxy in xserver's libglx, but the fatal error on resolve
failure makes this a little awkward. My generated glx protocol code is
going to be wired up regardless of the gl extensions the renderer actually
supports, and while a well-behaved client isn't going to send a request
the connection doesn't support, I don't want a mischevious client to be
able to shoot down the entire X server. I could prevent this by mirroring
the same provider iteration walk in the generated code, but needing to do
that in two places instead of one kind of defeats the point of having
epoxy involved at all.
This change adds a failure handler that, if registered, is called instead
of abort. There's not much it can usefully do of course - I expect the
xserver handler will just chirp in the log and …
=> RFC: Add epoxy_set_resolver_failure_handler()

meson.build
It's used unconditionally, but defined only for shared builds. For
static builds define it but don't populate it.
=> meson: Define visibility flags for static builds

include/epoxy/common.h, src/dispatch_common.c, src/dispatch_common.h
The EGL_EXT_device_query extension introduces the
eglQueryDeviceStringEXT() function, which can be used with an
EGLDeviceEXT enumeration to receive an OpenGL extension string
containing all of the device extensions supported by it. From the
EGL_EXT_device_query spec's amendments to section "3.2 Devices" after
"3.1 Errors":
const char *eglQueryDeviceStringEXT(EGLDeviceEXT device,
EGLint name);
returns a pointer to a static, zero-terminated string describing
some aspect of the specified EGLDeviceEXT.  <name> must be
EGL_EXTENSIONS.
Since OpenGL extension parsing is rather simple, and we could always run
into additional cases similar to this one in the future, we expose the
shared epoxy_extension_in_string() function in libepoxy's public headers
so that users can save themselves the hassle …
=> Expose epoxy_extension_in_string() in public headers

src/dispatch_common.c
Both gcc and clang define `__ANDROID__` but not `ANDROID` when targeting Android so
at least with the Meson build, and an NDK r16 toolchain, testing on
Android failed without this change.
Afaik `ANDROID` gets defined by `ndk-build` which is one reason to see code check that instead, but I'm not sure what ensured it was defined for whoever originally added the Android support to libepoxy. Maybe they used an external Android.mk based build or just added `-DANDROID` to their cflags, not sure.
=> Check __ANDROID__ define when guarding Android code

test/dlwrap.c
Add libOpenGL to the list of libraries we'll intercept. This is harmless
if glvnd is not available as the dlopen(libOpenGL.so) will fail, but
without this we can't intercept glGetString, which the
egl_and_glx_different_pointers_glx test needs to be able to do.
=> test: Fix dlwrap for glvnd

test/Makefile.am
Fix two tests that are linking to -ldl directly to use DLOPEN_LIBS. This
fixes failing test build on Gentoo/FreeBSD.
=> test: Fix respecting $(DLOPEN_LIBS)

src/dispatch_common.c, src/dispatch_wgl.c, test/dlwrap.c, test/egl_and_glx_different_pointers.c, test/egl_gl.c, test/glx_common.c, test/glx_public_api.c, test/glx_public_api_core.c, test/glx_static.c, test/khronos_typedefs_nonepoxy.c, test/wgl_common.c, test/wgl_core_and_exts.c, test/wgl_per_context_funcptrs.c, test/wgl_usefontbitmaps.c
- Fix use of `asprintf` to be correct and silence compiler warnings
- Only use `fprintf` when actually needed, otherwise use `fputs` (avoid unnecessary allocations)
=> Fix printf family usage

test/egl_without_glx.c
The NVIDIA driver calls dlopen with NULL as filename; strcmp is not
NULL-safe.
=> test: Avoid egl_without_glx crash on NVIDIA

src/meson.build
Even though meson will find the dependency gl on macOS, this does not mean that
there is a pkg-config file for it, as meson does not use pkg-config to
establish its presence. It should therefore not be added to
the libepoxy pkg-config file as a (private) requirement.
=> meson: do not add gl to pkg-config file on macOS

src/dispatch_common.c
errx() calls exit(), you'd rather get a backtrace.
=> dispatch: assert, not errx, when we have no context

test/glx_public_api_core.c
If you've built Mesa with --disable-texture-float, and try to run the
tests against Xvfb, glx_public_api_core will fail: creating a direct
context with llvmpipe will fail because you don't have
ARB_texture_float, and the internal fallback to an indirect context will
fail because indirect only supports through 1.4. So the server will
throw GLXBadFBConfig at you to say "I don't support core contexts",
which we should interpret as a skip not a failure.
=> test/glx_public_api_core: Fail softer if core contexts aren't available

src/dispatch_common.c, src/dispatch_common.h, src/dispatch_egl.c, src/dispatch_glx.c
This explicitly separates the dlopen and dlsym phases of every library, exposes the GLX and EGL loading logic to the rest of the library, and treats RTLD_NOLOAD and fatal-lookup-error as separate flags.
=> Make epoxy_load_{egl,glx} load libraries if they exist

test/dlwrap.c, test/meson.build
This pull request fixes the compilation error and add a symbol version for dlwrap on FreeBSD. It doesn't fix the test because of the lack of libglvnd.
=> Fix dlwrap for FreeBSD

src/dispatch_common.h
Our caller may load (eg) epoxy_glAlphaFunc, which is a function pointer,
and then call through that value multiple times. Until the caller
re-examines the value of that function pointer, which is a copy
relocation in the executable, repeated calls mean repeated work
resolving the GL function.
We can't make the caller reinspect the variable, but the resolver
function can avoid doing redundant work.
Fixes: anholt/libepoxy#171
=> dispatch: Try harder to avoid calling the resolver

test/egl_epoxy_api.c, test/egl_has_extension_nocontext.c
The strdup() function is available on uClibc if _XOPEN_SOURCE_EXTENDED
is defined; since we're using _GNU_SOURCE elsewhere to enable extended
libc features, and uClibc will set _XOPEN_SOURCE_EXTENDED if _GNU_SOURCE
is set, let's use that.
Closes #181
=> Define _GNU_SOURCE for strdup()

src/dispatch_common.c
Looking for a symbol named "libGLESv2.so.2" is probably not going to
work very well.
=> dispatch: Fix GLES3 symbol lookup

configure.ac
The X11 support in the Autotools build is missing the definition of the
ENABLE_X11 pre-processor symbol. Without it, we're missing the X11
platform definitions for EGL.
Fixes #188
=> Ensure Autotools enables EGL-X11 support

test/Makefile.am, test/gl_version.c, test/meson.build
Based on a bug report I got on IRC.  I thought parsing might be broken on their strings, but it worked fine.  Seems like a good test to have for future reports, though.
=> test: Add unit tests for epoxy_gl_version() and epoxy_glsl_version().

src/gen_dispatch.py
I saw ajax's suggestion, and it sounded like fun, so here goes.  Tested only with the testsuite, though the testsuite did catch bugs as I built this.  Release build sizes as we go:
```
1121212	  56800	    160	1178172	 11fa3c	master.so
1114236	  56800	    160	1171196	 11defc	providernames.so
1099948	  56800	    160	1156908	 11a72c	enumstrings.so
```
I think the next step would be to sort the providers into "GL versions" and "Extensions" and have the provider resolve loop be "check GL version for providers < cutoff and check GL/GLX/whatever extension for providers >= cutoff.
Fixes #202
=> enum names

test/egl_epoxy_api.c, test/egl_has_extension_nocontext.c
Needed to allow functions outside the original XPG3 standard to be
visible in the Solaris headers when _XOPEN_SOURCE is defined and
not set to a particular value.
Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
=> test: #define __EXTENSIONS__ on Solaris for strdup()

test/meson.build
Fixes build failure when x11 is not found or disabled and glx is also not found. To reproduce, build with:
`PKG_CONFIG_LIBDIR='' meson _build`
The proper fix involves reorganising the dependency checking logic to use Feature Options instead of a combo with auto/yes/no, but that's a larger patch that I'll add later.
=> meson: Don't build glx tests if x11 is disabled

configure.ac, include/epoxy/meson.build, meson.build, src/gen_dispatch.py, src/meson.build
Python 2 is going to reach EOL in January 2020, and most platforms have
already moved to Python 3.
=> Remove Python 2 support

.travis.yml, meson.build
Do not rely on the shebang line and the executable bit; we should use
find_program(), instead, which lets Meson run a script in the
appropriate environment, portably.
=> build: Use find_program()

src/dispatch_common.h
MESA_EGL_NO_X11_HEADERS has been deprecated, and libglvnd only supports
EGL_NO_X11.
Fixes: #214
=> Use EGL_NO_X11 to disable X11 headers

src/dispatch_common.c, test/gl_version.c
Throughout the mesa project we've been using 100 for GLES2's shading
language.  It was pretty clearly the intent here, but the clever
inline detection of "am I parsing a GLSL version or a GL version
string" forgot about GLSL 1.0.x, and thus returned 10.
=> Fix return value of shading language for GLES2.

meson.build, src/meson.build
GTK currently fails to detect if epoxy has been built with EGL on
Windows when epoxy is a subproject. To fix that it needs to get that
information from the dependency variables.
=> meson: Set same variables in declare_dependency() as in pkgconfig

src/dispatch_common.c
=> Fix some bugs in loading OpenGL/GLX/EGL libraries

src/gen_dispatch.py
So all buffered data actually gets written.
Fixes https://github.com/anholt/libepoxy/issues/242
=> gen_dispatch.py: close output files

src/gen_dispatch.py
The type is being redeclared because I didn't see the original
declaration when I wrote 144cbc9325250081f2eb584ca5deb13aaf1c2433.
Fixes: #249
=> Remove redeclaration of khronos_uintptr_t

src/dispatch_common.c
This maintains compatibility with previous behavior of
always using GLX_LIB if it is found. The only change is
when there is no GLX_LIB.
Previous behavior when no GLX_LIB:
- abort.
New behavior when no GLX_LIB:
- Try to load libOpenGL.so as gl_handle (glx_handle remains NULL).
- Else, abort.
=> Allow libopengl.so to be used when GLX_LIB is missing

meson.build, src/meson.build
Currently the build works on most systems since these headers are
usually installed in the same directory as other dependencies or in
the default include directory. However, on some platforms the X11/GL
headers are installed to a different prefix, and then the build fails
due to missing includes.
=> Fix build if EGL/X11 headers are in a custom prefix

meson.build
Specify utf-8 encoding to fix building on non-English locale
=> meson: Fix for building on non-English locale

src/meson.build
With this change, libepoxy can be consumed as a subproject without making any changes to the build files of a project. All you need to do is provide a wrap file with a `[provide]` section:
https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section
This is also necessary because otherwise projects need to hard-code the subproject name, which might be `libepoxy` when using `wrap-git` or `libepoxy-1.5.10` when using `wrap-file` (to build from a release tarball). This can cause conflicts between different subprojects that consume libepoxy differently.
Other projects like glib, cairo, pango, etc already do this.
=> meson: Override dependency to improve usage as a subproject

meson.build, src/meson.build
This change allows to build & use libepoxy in a wayland environment without libX11 (as libGL.so depends on it for glx).
There is also a separated "glx" library but that would require more changes to the meson code and I'm not sure if it would be useful to libepoxy.
=> meson.build: Fallback from libGL to libOpenGL when GLX is disabled

src/dispatch_common.c
Libepoxy may be built with support for EGL, but may run on trimmed-down systems which do not expose EGL. Or it may run in a sandbox which doesn't expose the EGL library. Check for EGL support at runtime before calling into EGL functions
Fixes https://gitlab.com/inkscape/inkscape/-/issues/4031
=> Check for EGL support at runtime before calling into EGL functions

include/epoxy/gl.h
This avoids redefinition warnings when including epoxy/gl.h before windows.h
=> Define APIENTRY the same way its defined in windows.h

test/dlwrap.c
See [sysdeps/unix/sysv/linux/riscv/rv64/libdl.abilist](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/riscv/rv64/libdl.abilist;h=33ff573df8748197102314b6ca7579e060c7b8ad) in glibc's source.
=> test: Fix dlwrap on riscv64
